clear all;clc;
g = gpuDevice(2);
reset (g);
%% Load training set
load dCullTrain.mat;
%% Build a network
inputSize = 40;
numHiddenUnits1 = 2000;
numHiddenUnits2 = 2000;
numClasses = 3;
layers = [ ...
    sequenceInputLayer(inputSize)
    bilstmLayer(numHiddenUnits1,'OutputMode','sequence')
    dropoutLayer(0.2)
    bilstmLayer(numHiddenUnits2,'OutputMode','sequence')
    dropoutLayer(0.2)
    fullyConnectedLayer(numClasses)
    softmaxLayer
    classificationLayer];
options = trainingOptions('adam', ...
    'ExecutionEnvironment','gpu', ...
    'MaxEpochs',10,...
    'MiniBatchSize',3,...
    'GradientThreshold',1, ...
    'L2Regularization',0.000001,...
    'InitialLearnRate',0.0001, ...%%%%%%
    'LearnRateSchedule','piecewise', ...
    'LearnRateDropPeriod',4, ... 
    'SequenceLength','longest', ...
    'SequencePaddingValue',0, ...
    'shuffle','never', ...
    'Verbose',true, ...
    'Plots','training-progress');
net = trainNetwork(X_train,Y_train,layers,options);